version: "3.7"
services:
  # Nginx Service
  nginx:
    container_name: nginx-l
    build:
      context: ./etc/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./src/backend
        target: /var/www/html
    networks:
      - laravelnet
networks:
  laravelnet:
    driver: bridge