version: "3.7"
services:
  # Nginx Service
  nginx:
    container_name: nginx-l
    build:
      context: ./etc/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./src/backend
        target: /var/www/html
    networks:
      - laravelnet
  # web Service
  app:
    container_name: app-l
    build:
      context: ./etc/app
      dockerfile: Dockerfile
      args:
        user: nima
        uid: 1000
    restart: always
    volumes:
      - type: bind
        source: ./src/backend
        target: /var/www/html
      - type: bind
        source: ./etc/app/local.ini
        target: /usr/local/etc/php/conf.d/local.ini
    networks:
      - laravelnet
  # Mysql
  mysql:
    container_name: mysql-l
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - type: bind
        source: ./etc/mysql/my.conf
        target: /etc/mysql/conf.d/my.cnf
      - type: volume
        source: laravelData
        target: /var/lib/mysql
    networks:
      - laravelnet
  # Frontend Service
  frontend:
    container_name: frontend-l
    image: node:12-alpine
    working_dir: /var/www/html
    volumes:
      - type: bind
        source: ./src/backend
        target: /var/www/html
    networks:
      - laravelnet
networks:
  laravelnet:
    driver: bridge
volumes:
  laravelData: